import Gluck.Figures.Specs

/-! Deterministic export of the shared blueprint figure parameters. -/

namespace Gluck.Figures

private def texParameters : String :=
  "% Generated by `lake exe gluckFigures`; do not edit.\n" ++
  "\\def\\EuclideanOpenA{0.25}\n" ++
  "\\def\\EuclideanB{0.1666666667}\n" ++
  "\\def\\SphereRadius{0.5}\n" ++
  "\\def\\SphereCurvature{0.75}\n" ++
  "\\def\\HyperbolicCOne{2}\n" ++
  "\\def\\HyperbolicCTwo{1.2}\n" ++
  "\\def\\HyperbolicCThree{1.02}\n"

private def jsonManifest : String :=
  "{\n" ++
  "  \"schemaVersion\": 1,\n" ++
  "  \"figures\": [\n" ++
  "    {\n" ++
  "      \"id\": \"euclidean-closure\",\n" ++
  "      \"parameters\": { \"openA\": 0.25, \"closedA\": 0, \"b\": 0.1666666667 }\n" ++
  "    },\n" ++
  "    {\n" ++
  "      \"id\": \"sphere-stereographic\",\n" ++
  "      \"parameters\": { \"radius\": 0.5, \"curvature\": 0.75 }\n" ++
  "    },\n" ++
  "    {\n" ++
  "      \"id\": \"hyperbolic-escape\",\n" ++
  "      \"parameters\": { \"curvatureLevels\": [2, 1.2, 1.02] }\n" ++
  "    }\n" ++
  "  ]\n" ++
  "}\n"

def exportMain (args : List String) : IO Unit := do
  let outputDir ← match args with
    | [path] => pure (System.FilePath.mk path)
    | _ => throw <| IO.userError "usage: lake exe gluckFigures OUTPUT_DIRECTORY"
  IO.FS.createDirAll outputDir
  IO.FS.writeFile (outputDir / "figure-params.tex") texParameters
  IO.FS.writeFile (outputDir / "figures.json") jsonManifest

end Gluck.Figures

def main (args : List String) : IO Unit :=
  Gluck.Figures.exportMain args
